### ISSUE TITLE
Support filter key match from start

### ISSUE THREAD

**Issue by zyf0330** [gtamas/etcdmanager#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Now filter key just match text occurs in key, I want to match from start just.
**Describe alternatives you've considered**

**Additional context**

**Comment by gtamas** [comment]
Currently we match the whole text of a label / value, so matching from start is kinda included as well. 
I mean, if you have key "foobar" and you are searching for "foo", then it's gonna find your key. Although matching happens differently, the expected result will still be produced. 

So I'm closing this for now. We have plans for adding advanced filtering capabilities in the future, so stay tuned :)

**Comment by zyf0330** [comment]
I want to just match from start to avoid match those same text in middle.
Hope to see advanced filter feature.
