### ISSUE TITLE
[BUG] Not able to do much unless the user is root

### ISSUE THREAD

**Issue by Maha-Weinvest-zz** [gtamas/etcdmanager#19]
**Describe the bug**

Nothing seems to work for a non-root user, despite the non-root user having read permission for all keys

**To Reproduce**

1. Add User test
2. Add Role test
3. Grant all permissions via `etcdctl role test grant-permission read /pub/`
4. In ETCD Manager, set AUTH sections to test user credentials
5. Test connection 
Test Connection fails with "Permission denied"
7. Navigate to Manage Keys
Unable to see any keys

**Expected behavior**

- Test connection should work fine
- Navigating to Manage Keys section should show all keys

**Desktop (please complete the following information):**
 - MacOS ETCD Manager v1.0.0
- etcd version 3.2.26

**Comment by gtamas** [comment]
Thanks for reporting this bug. We'll look into it and will keep you posted.

**Comment by gtamas** [comment]
Heads up: We are working on this right now, it'll be fixed in the next release (1.1).

**Comment by gtamas** [comment]
This is now fixed in master. Binaries will be release later today, closing..
