### ISSUE TITLE
More Etcd server connection

### ISSUE THREAD

**Issue by speter555** [gtamas/etcdmanager#22]
**Is your feature request related to a problem? Please describe.**
My problem is that I have more enviroments, and I would like to management more etcd servers than one.

**Describe the solution you'd like**
Can add more etcd connection

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by gtamas** [comment]
@speter555 

Yes, this is gonna be part of the next release. It's already implemented. We gonna release this ASAP.
