### ISSUE TITLE
Build docker image and publish to docker-hub

### ISSUE THREAD

**Issue by dusktreader** [gtamas/etcdmanager#33]
**Is your feature request related to a problem? Please describe.**
I would like to be able to spin up the etcdmanager app in concert with etcd itself in a single docker-compose/docker-swarm.

**Describe the solution you'd like**
It would be great to have a docker image that can be pulled down from docker hub easily.

**Describe alternatives you've considered**
I've considered spinning up a new docker repo myself and building some images, but I'm not sure I have time to do that right now

**Additional context**
I really like the appearance of this etcd-ui in comparison with others I've seen. However, the lack of a published docker image is a big draw-back

**Comment by gtamas** [comment]
We looked into this and it's problematic. ETCD maneger is a GUI app and it's not easy to make those work with Docker. It could be done, but probably it wouldn't work very well and it wouldn't support some OSes.

We might get back to this if we find a better solution and of course contributions are always welcome. However, for now I'm closing this one.
