### ISSUE TITLE
[FEATURE] Show connected etcd environment in letterhead

### ISSUE THREAD

**Issue by gergelybosze** [gtamas/etcdmanager#34]
**Is your feature request related to a problem? Please describe.**
The app would be more transparent, especially when using 'Manage keys', if I can see the loaded profile name and the connected environment in the letterhead (picture attached).
![etcdmanager110fr show connected env](https://user-images.githubusercontent.com/25009457/72966104-56596080-3dbe-11ea-987c-d77b237696a6.png)

**Describe the solution you'd like**
When I load a profile in 'Settings', the letterhead text must be changed.
Example:
ETCD Manager v1.1.0 - DEV - localhost:2379
ETCD Manager v1.1.0 - DEV2 - localhost:23792

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by gtamas** [comment]
This will be added in the next release.

**Comment by gtamas** [comment]
Fixed in develop
