### ISSUE TITLE
How can I use TLS?

### ISSUE THREAD

**Issue by cwilgo** [gtamas/etcdmanager#35]
With etcdctl there are options: --cacert, --cert, --key, etc. for using etd's TLS transport security options. I can't seem to find a way to use these features with ETCD Manager. Is there a way to set these?

**Comment by gtamas** [comment]
Not yet, but we will add this in the upcoming version. We'll keep you posted.

**Comment by gtamas** [comment]
Already implemented in develop, gonna release soon.
