### ISSUE TITLE
[BUG]intranet cannot work fine

### ISSUE THREAD

**Issue by cdyue** [gtamas/etcdmanager#36]
**Describe the bug**
When used in an intranet environment, it does not work properly.  Maybe etcdmanager needs internet resource just like js,css,etc.

**To Reproduce**
any environment can't connect to internet, open etcdmanager.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7218849/75307687-4fbf7c80-5887-11ea-98ad-e1babd7e8081.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15
 - ETCD manager version:1.1

**Additional context**

**Comment by gtamas** [comment]
This fill be fixed in next release

**Comment by gtamas** [comment]
Already fixed in develop branch, will be released soon.

**Comment by cdyue** [comment]
@gtamas  thank you！
