### ISSUE TITLE
etcdmanager not able to connect to IBM Cloud ETCD service

### ISSUE THREAD

**Issue by Ravenwater** [gtamas/etcdmanager#47]
**App and environment info (please complete the following information):**
 - OS: Windows 10 Pro
 - OS version 1903
 - ETCD manager version [v.1.1.0]
 - Virtualisation tech used (if any) none

**How can we help?.**
Trying to connect to an IBM Cloud ETCD service, but username field validation rejects the username that IBM Cloud etcd supports, which includes _ : password is rejected with the error "Alphanumeric value expected"

**Comment by gtamas** [comment]
OK will add this in the next release (1.2) which is coming soon.

**Comment by Ravenwater** [comment]
that would be most splendid. I love to bring this into the IBM Cloud operations side.

**Comment by gtamas** [comment]
Already fixed in develop branch. Release is currently under QA testing.

**Comment by gtamas** [comment]
Released, try 1.2.
