### ISSUE TITLE
[BUG] After downloading and installing the etcd-1.0.0 for linux, I see white screen when the etcd-manager is opened 

### ISSUE THREAD

**Issue by khoi-vo** [gtamas/etcdmanager#6]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS version [e.g. 22]
 - ETCD manager version [e.g. 1.2]

**Additional context**

**Comment by gtamas** [comment]
Which package are we talking about? The AppImage or TGZ?
Also, please provide more info, like which linux is this, which version etc.
Thanks!

**Comment by gtamas** [comment]
In the meantime, I just looked into this.
Something seems to be wrong with the Linux packages indeed. We are working on it and we gonna publish a fix soon.

**Comment by gtamas** [comment]
Problem fixed. This should run fine on Ubuntu 18.04 LTS or newer.
Unless your OS is older, please try again now.

**Comment by gtamas** [comment]
Seems to be solved by latest release (see above). Please reopen if needed.
