### ISSUE TITLE
Add certificate based on authentication

### ISSUE THREAD

**Issue by aeoluswing** [gtamas/etcdmanager#64]
**Is your feature request related to a problem? Please describe.**

If etcd cluster using certificate to satisfy tls handshake,what should i do for this gui client?Baisc auth (username and password)is not enough for https transport in development or production cluster.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gtamas** [comment]
Yeah, this is implemented in 1.2, which is currently under QA testing. You can already find this functionality in the develop branch as well, if you wanna give it a try.  The next release will support HTTPS connect and certificates as well.

We'll ping you as soon as it's released
