### ISSUE TITLE
[BUG]cannot save or load profile: Could not perform operation. Error: Error: 14 UNAVAILABLE: Empty update

### ISSUE THREAD

**Issue by watermeion** [gtamas/etcdmanager#72]
**Describe the bug**
can not save profile

**To Reproduce**
open app at first time

**Screenshots**
Could not perform operation. Error: Error: 14 UNAVAILABLE: Empty update

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.5
 - ETCD manager version 1.2.0

**Comment by gtamas** [comment]
Thanks. Will look into this as soon as I can

**Comment by gtamas** [comment]
Actually, I'm closing this one. It's a duplicate of:

https://github.com/gtamas/etcdmanager/issues/73

Please check that issue for updates.
