### ISSUE TITLE
[BUG]not support @ in password when auth

### ISSUE THREAD

**Issue by cdyue** [gtamas/etcdmanager#8]
**Describe the bug**
Only support alphaNum in password now, but need to support such as @,!.

**Comment by gtamas** [comment]
@cdyue 
Yeah makes sense. We are working on it, and this issue will be properly addressed in the next release. We'll keep you posted.

**Comment by kesavkolla** [comment]
yes my password also has a non alphanum character.  Can't use etcdmanager because of that.

**Comment by gtamas** [comment]
@kesavkolla @cdyue 
The fix has been merged into master, you should be able to use any UTF8 string now. We will publish a new binary release later this week.
Should the problem resurface, please reopen!

**Comment by cdyue** [comment]
@gtamas Thanks.
